### ISSUE TITLE
Add profiles-controller ClusterRoleBindings

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/charts#107]
We need to add a `ClusterRoleBinding` to the profiles-controller service account for every `ClusterRole` mentioned here

https://github.com/StatCan/aaw-kubeflow-profiles-controller/blob/main/cmd/rbac.go

Otherwise we have permission errors.

Someone should add `clusterRoleBindings: []` to the values.yaml file, and have it create the cluster role bindings in a loop and attach them to the profiles controller

**Comment by sylus** [comment]
@zachomedia can you comment on this doesn't seem right to me?

**Comment by blairdrummond** [comment]
I think another option is @zachomedia 's magic to allow a role to create rolebindings to resources it doesn't have access to (escalation)

**Comment by zachomedia** [comment]
This is already done for `profile-support` https://github.com/StatCan/charts/blob/master/stable/profiles-controller/templates/clusterrole.yaml#L101

You just need to add the other cluster role to the list in the chart.
