### ISSUE TITLE
Fix fluentd configmap name

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/charts#181]
Hey @menmarc we need to rename your [fluentd configmap name](https://github.com/StatCan/charts/blob/master/stable/disclosure-vetting-application/templates/fluentd-configmap.yaml#L5), try `vetting-fluentd-config`. It's going to get overridden by terraform, which will mess with your app. We'll add a modification to the terraform for your namespace in order to use this:

```bash
# YOU DON'T RUN THIS. We will do this in terraform instead
# The following step is optional: the fluentd-config is the default configmap name.
# kubectl annotate namespace demo logging.csp.vmware.com/fluentd-configmap=vetting-fluentd-config
```

See https://github.com/vmware/kube-fluentd-operator#try-it-out

**Comment by menmarc** [comment]
@mathis-marcotte can you change our file to "vetting-fluentd-config" and delete the existing one ? Thanks!

**Comment by blairdrummond** [comment]
I will fix that now!

**Comment by blairdrummond** [comment]
Try now @menmarc ?

**Comment by mathis-marcotte** [comment]
Hi @blairdrummond , Logs still seem to not be going through.

**Comment by menmarc** [comment]
@blairdrummond any idea how to fix this ?

**Comment by menmarc** [comment]
@blairdrummond any updates on this ? this is vital for us to have elastic search working in DEV and i'm assuming in prod too.

**Comment by chuckbelisle** [comment]
Made minor changes to the chart and updated the both dev and prod aaw infrastructure terraform deployment for org-ces-system.

Changes have run through CI/CD successfully for DEV and are ready to test. Prod CI/CD is currently running and will be ready for validation in about 20 minutes.

**Comment by mathis-marcotte** [comment]
I tested DEV and we are still not getting logs in elastic search

**Comment by chuckbelisle** [comment]
Give it another try both in dev and prod. If you still see an issue, it would be great if you could provide more information to this ticket.

**Comment by menmarc** [comment]
@chuckbelisle in DEV it's working fine, in prod we'll try to test this once the infrastructure is back online.

**Comment by blairdrummond** [comment]
Can you retry @menmarc ?

**Comment by menmarc** [comment]
@mathis-marcotte can you confirm that it is resolved. I think so!

**Comment by menmarc** [comment]
@blairdrummond can you assist us with this issue ? everything was working fine before the azure update  (that broke the network)

**Comment by chuckbelisle** [comment]
@menmarc & @mathis-marcotte we were under the impression that this ticket was resolved when confirmation was given that logs were streaming to both DEV and PROD.
If it is the same issue and logs are no longer streaming, let's reuse this ticket, but if it's different, let's open a new one with all the details we require to troubleshoot the issue.

We want this to work for you. Moving forward, please reach out to me directly next time something comes up with this effort. (use Slack DMs or Teams)

I will schedule some time with one of our developers to meet internally and then with you this week.

cc: @dajadam @brendangadd

**Comment by blairdrummond** [comment]
Can you check Dev now @menmarc ? 

(@brendangadd Fluentd runs on the node, so an internal elastic url doesn't work. I am temporarily using the public ingress on dev, until I figure out the dns details of the internal ingress gateway)

**Comment by mathis-marcotte** [comment]
Yes DEV logs are indeed going through.

**Comment by blairdrummond** [comment]
Closing

**Comment by dajadam** [comment]
A new elastic URL needs to be created for Dev and Prod - a ticket for this task has been created: https://github.com/StatCan/daaas/issues/881
