### ISSUE TITLE
Chart depoyment error

### ISSUE THREAD

**Issue by menmarc** [StatCan/charts#47]
I'm getting an error (see step with X)

https://github.com/StatCan/charts/runs/3341380396?check_suite_focus=true

error: Your local changes to the following files would be overwritten by checkout:
stable/ckan/charts/datapusher-1.0.0.tgz
stable/ckan/charts/solr-1.5.6.tgz

Not sure if this has an impact on our CI/CD workflow. Can you confirm ?

Thanks!

**Comment by blairdrummond** [comment]
The issue is you need to `cd` into `stable/ckan` and do a `helm repo update`; then commit that. But that's annoying to do every time, I will try to fix the chart so that it isn't causing this issue

**Comment by sylus** [comment]
@zachomedia 

I think this might fix the issue once and for all?

https://github.com/StatCan/actions/commit/e964212cde677bd2bb3bdcac49f8ca6167bc1a09
